export const mockDataTruthOrLie = {
  "1": [
    { number: 1, text: "The sky is blue.", answer: true },
    { number: 2, text: "Cats can fly.", answer: false },
    { number: 3, text: "Fish live in water.", answer: true },
    { number: 4, text: "The sun is cold.", answer: false },
    { number: 5, text: "Dogs have four legs.", answer: true },
    { number: 6, text: "We eat soup with a fork.", answer: false },
    { number: 7, text: "Apples are fruits.", answer: true },
    { number: 8, text: "The moon is made of cheese.", answer: false },
    { number: 9, text: "You wear shoes on your feet.", answer: true },
    { number: 10, text: "Fire is hot.", answer: true },
  ],
  "2": [
    { number: 1, text: "Birds can sing.", answer: true },
    { number: 2, text: "Sugar tastes sweet.", answer: true },
    { number: 3, text: "Books are for eating.", answer: false },
    { number: 4, text: "The ocean is full of water.", answer: true },
    { number: 5, text: "A bed is for sleeping.", answer: true },
    { number: 6, text: "Cows can drive cars.", answer: false },
    { number: 7, text: "Rain is wet.", answer: true },
    { number: 8, text: "We wear a hat on the head.", answer: true },
    { number: 9, text: "Bananas are blue.", answer: false },
    { number: 10, text: "Winter is usually cold.", answer: true },
  ],
  "3": [
    { number: 1, text: "Milk comes from cows.", answer: true },
    { number: 2, text: "People eat rocks for lunch.", answer: false },
    { number: 3, text: "Ice is frozen water.", answer: true },
    { number: 4, text: "The Earth is flat.", answer: false },
    { number: 5, text: "We use a key to open a door.", answer: true },
    { number: 6, text: "Cars can swim in the sea.", answer: false },
    { number: 7, text: "The clock shows the time.", answer: true },
    { number: 8, text: "Dogs usually meow.", answer: false },
    { number: 9, text: "Water is needed to live.", answer: true },
    { number: 10, text: "Pencils are for writing.", answer: true },
  ],
  "4": [
    { number: 1, text: "The phone is used for calling.", answer: true },
    { number: 2, text: "Shoes are worn on hands.", answer: false },
    { number: 3, text: "Bread is usually eaten.", answer: true },
    { number: 4, text: "The sun rises in the west.", answer: false },
    { number: 5, text: "A cat is an animal.", answer: true },
    { number: 6, text: "We drink coffee from a cup.", answer: true },
    { number: 7, text: "People usually sleep in the kitchen.", answer: false },
    { number: 8, text: "Clouds are in the sky.", answer: true },
    { number: 9, text: "The fridge keeps food cold.", answer: true },
    { number: 10, text: "Fish can walk on land.", answer: false },
  ],
  "5": [
    { number: 1, text: "Most people have two eyes.", answer: true },
    { number: 2, text: "A chair is for sitting.", answer: true },
    { number: 3, text: "Cats usually like water.", answer: false },
    { number: 4, text: "A bus carries many people.", answer: true },
    { number: 5, text: "We use soap to wash our hands.", answer: true },
    { number: 6, text: "The stars shine at night.", answer: true },
    { number: 7, text: "Elephants are small animals.", answer: false },
    { number: 8, text: "Children go to school.", answer: true },
    { number: 9, text: "Pizza is a kind of food.", answer: true },
    { number: 10, text: "The moon shines in the daytime only.", answer: false },
  ],
  "6": [
    { number: 1, text: "The Earth has one moon.", answer: true },
    { number: 2, text: "The internet is older than books.", answer: false },
    { number: 3, text: "Rain falls from clouds.", answer: true },
    { number: 4, text: "Mountains are flat.", answer: false },
    { number: 5, text: "Airplanes can fly in the sky.", answer: true },
    { number: 6, text: "The desert is full of water.", answer: false },
    { number: 7, text: "Trees make oxygen.", answer: true },
    { number: 8, text: "Penguins live in the Arctic.", answer: false },
    { number: 9, text: "Honey comes from bees.", answer: true },
    { number: 10, text: "Lions are wild animals.", answer: true },
  ],
  "7": [
    { number: 1, text: "The capital of France is Paris.", answer: true },
    { number: 2, text: "Water boils at 0 degrees Celsius.", answer: false },
    { number: 3, text: "The Amazon is a big river.", answer: true },
    {
      number: 4,
      text: "Humans can breathe underwater without help.",
      answer: false,
    },
    { number: 5, text: "The Great Wall of China is in China.", answer: true },
    { number: 6, text: "The camel lives in the desert.", answer: true },
    { number: 7, text: "Sharks are birds.", answer: false },
    { number: 8, text: "Volcanoes can erupt.", answer: true },
    { number: 9, text: "Chocolate is made from cocoa beans.", answer: true },
    { number: 10, text: "A year has 100 days.", answer: false },
  ],
  "8": [
    { number: 1, text: "The human heart has four chambers.", answer: true },
    { number: 2, text: "Saturn is a planet with rings.", answer: true },
    {
      number: 3,
      text: "Whales are the largest animals on Earth.",
      answer: true,
    },
    { number: 4, text: "Tomatoes grow underground.", answer: false },
    { number: 5, text: "Electricity powers lights.", answer: true },
    { number: 6, text: "The Pacific is the smallest ocean.", answer: false },
    { number: 7, text: "Spiders have eight legs.", answer: true },
    { number: 8, text: "The Eiffel Tower is in Rome.", answer: false },
    { number: 9, text: "Blood is red.", answer: true },
    { number: 10, text: "Deserts are usually hot.", answer: true },
  ],
  "9": [
    { number: 1, text: "A leap year has 366 days.", answer: true },
    { number: 2, text: "Oxygen is needed to breathe.", answer: true },
    { number: 3, text: "The capital of Japan is Tokyo.", answer: true },
    { number: 4, text: "Water is heavier than metal.", answer: false },
    { number: 5, text: "The Sahara is the largest hot desert.", answer: true },
    { number: 6, text: "Sound travels faster than light.", answer: false },
    { number: 7, text: "Dinosaurs are still alive today.", answer: false },
    { number: 8, text: "The human brain controls the body.", answer: true },
    { number: 9, text: "The North Pole is very cold.", answer: true },
    { number: 10, text: "All snakes are poisonous.", answer: false },
  ],
  "10": [
    { number: 1, text: "The Earth orbits the Sun.", answer: true },
    {
      number: 2,
      text: "The speed of light is faster than sound.",
      answer: true,
    },
    { number: 3, text: "Canberra is the capital of Australia.", answer: true },
    {
      number: 4,
      text: "The human body has 300 bones in adulthood.",
      answer: false,
    },
    { number: 5, text: "Pluto is no longer a planet.", answer: true },
    {
      number: 6,
      text: "Atoms are the building blocks of matter.",
      answer: true,
    },
    {
      number: 7,
      text: "The Atlantic Ocean is larger than the Pacific.",
      answer: false,
    },
    { number: 8, text: "Water is a chemical compound.", answer: true },
    { number: 9, text: "Albert Einstein discovered gravity.", answer: false },
    { number: 10, text: "Humans landed on the Moon in 1969.", answer: true },
  ],
};
