export const mockDataTruthOrLie = [
  { text: "The sky is blue.", answer: true },
  { text: "Cats can fly.", answer: false },
  { text: "Fish live in water.", answer: true },
  { text: "The sun is cold.", answer: false },
  { text: "Dogs have four legs.", answer: true },
  { text: "We eat soup with a fork.", answer: false },
  { text: "Apples are fruits.", answer: true },
  { text: "The moon is made of cheese.", answer: false },
  { text: "You wear shoes on your feet.", answer: true },
  { text: "Fire is hot.", answer: true },
  { text: "Birds can sing.", answer: true },
  { text: "Sugar tastes sweet.", answer: true },
  { text: "Books are for eating.", answer: false },
  { text: "The ocean is full of water.", answer: true },
  { text: "A bed is for sleeping.", answer: true },
  { text: "Cows can drive cars.", answer: false },
  { text: "Rain is wet.", answer: true },
  { text: "We wear a hat on the head.", answer: true },
  { text: "Bananas are blue.", answer: false },
  { text: "Winter is usually cold.", answer: true },
];
