export const mockDataTruthOrLie = {
  level1: [
    { text: "The sky is blue.", answer: true },
    { text: "Cats can fly.", answer: false },
    { text: "Fish live in water.", answer: true },
    { text: "The sun is cold.", answer: false },
    { text: "Dogs have four legs.", answer: true },
    { text: "We eat soup with a fork.", answer: false },
    { text: "Apples are fruits.", answer: true },
    { text: "The moon is made of cheese.", answer: false },
    { text: "You wear shoes on your feet.", answer: true },
    { text: "Fire is hot.", answer: true },
  ],
  level2: [
    { text: "Birds can sing.", answer: true },
    { text: "Sugar tastes sweet.", answer: true },
    { text: "Books are for eating.", answer: false },
    { text: "The ocean is full of water.", answer: true },
    { text: "A bed is for sleeping.", answer: true },
    { text: "Cows can drive cars.", answer: false },
    { text: "Rain is wet.", answer: true },
    { text: "We wear a hat on the head.", answer: true },
    { text: "Bananas are blue.", answer: false },
    { text: "Winter is usually cold.", answer: true },
  ],
  level3: [
    { text: "Milk comes from cows.", answer: true },
    { text: "People eat rocks for lunch.", answer: false },
    { text: "Ice is frozen water.", answer: true },
    { text: "The Earth is flat.", answer: false },
    { text: "We use a key to open a door.", answer: true },
    { text: "Cars can swim in the sea.", answer: false },
    { text: "The clock shows the time.", answer: true },
    { text: "Dogs usually meow.", answer: false },
    { text: "Water is needed to live.", answer: true },
    { text: "Pencils are for writing.", answer: true },
  ],
  level4: [
    { text: "The phone is used for calling.", answer: true },
    { text: "Shoes are worn on hands.", answer: false },
    { text: "Bread is usually eaten.", answer: true },
    { text: "The sun rises in the west.", answer: false },
    { text: "A cat is an animal.", answer: true },
    { text: "We drink coffee from a cup.", answer: true },
    { text: "People usually sleep in the kitchen.", answer: false },
    { text: "Clouds are in the sky.", answer: true },
    { text: "The fridge keeps food cold.", answer: true },
    { text: "Fish can walk on land.", answer: false },
  ],
  level5: [
    { text: "Most people have two eyes.", answer: true },
    { text: "A chair is for sitting.", answer: true },
    { text: "Cats usually like water.", answer: false },
    { text: "A bus carries many people.", answer: true },
    { text: "We use soap to wash our hands.", answer: true },
    { text: "The stars shine at night.", answer: true },
    { text: "Elephants are small animals.", answer: false },
    { text: "Children go to school.", answer: true },
    { text: "Pizza is a kind of food.", answer: true },
    { text: "The moon shines in the daytime only.", answer: false },
  ],
  level6: [
    { text: "The Earth has one moon.", answer: true },
    { text: "The internet is older than books.", answer: false },
    { text: "Rain falls from clouds.", answer: true },
    { text: "Mountains are flat.", answer: false },
    { text: "Airplanes can fly in the sky.", answer: true },
    { text: "The desert is full of water.", answer: false },
    { text: "Trees make oxygen.", answer: true },
    { text: "Penguins live in the Arctic.", answer: false },
    { text: "Honey comes from bees.", answer: true },
    { text: "Lions are wild animals.", answer: true },
  ],
  level7: [
    { text: "The capital of France is Paris.", answer: true },
    { text: "Water boils at 0 degrees Celsius.", answer: false },
    { text: "The Amazon is a big river.", answer: true },
    { text: "Humans can breathe underwater without help.", answer: false },
    { text: "The Great Wall of China is in China.", answer: true },
    { text: "The camel lives in the desert.", answer: true },
    { text: "Sharks are birds.", answer: false },
    { text: "Volcanoes can erupt.", answer: true },
    { text: "Chocolate is made from cocoa beans.", answer: true },
    { text: "A year has 100 days.", answer: false },
  ],
  level8: [
    { text: "The human heart has four chambers.", answer: true },
    { text: "Saturn is a planet with rings.", answer: true },
    { text: "Whales are the largest animals on Earth.", answer: true },
    { text: "Tomatoes grow underground.", answer: false },
    { text: "Electricity powers lights.", answer: true },
    { text: "The Pacific is the smallest ocean.", answer: false },
    { text: "Spiders have eight legs.", answer: true },
    { text: "The Eiffel Tower is in Rome.", answer: false },
    { text: "Blood is red.", answer: true },
    { text: "Deserts are usually hot.", answer: true },
  ],
  level9: [
    { text: "A leap year has 366 days.", answer: true },
    { text: "Oxygen is needed to breathe.", answer: true },
    { text: "The capital of Japan is Tokyo.", answer: true },
    { text: "Water is heavier than metal.", answer: false },
    { text: "The Sahara is the largest hot desert.", answer: true },
    { text: "Sound travels faster than light.", answer: false },
    { text: "Dinosaurs are still alive today.", answer: false },
    { text: "The human brain controls the body.", answer: true },
    { text: "The North Pole is very cold.", answer: true },
    { text: "All snakes are poisonous.", answer: false },
  ],
  level10: [
    { text: "The Earth orbits the Sun.", answer: true },
    { text: "The speed of light is faster than sound.", answer: true },
    { text: "Canberra is the capital of Australia.", answer: true },
    { text: "The human body has 300 bones in adulthood.", answer: false }, // 206
    { text: "Pluto is no longer a planet.", answer: true },
    { text: "Atoms are the building blocks of matter.", answer: true },
    { text: "The Atlantic Ocean is larger than the Pacific.", answer: false },
    { text: "Water is a chemical compound.", answer: true },
    { text: "Albert Einstein discovered gravity.", answer: false }, // это Ньютон
    { text: "Humans landed on the Moon in 1969.", answer: true },
  ],
};
